name: User Registration Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username del usuario'
        required: true
        type: string
      email:
        description: 'Email del usuario'
        required: true
        type: string
      password:
        description: 'Contraseña del usuario'
        required: true
        type: string

jobs:
  register-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Register User
        id: register
        run: |
          response=$(curl -s -o response_body.txt -w "%{http_code}" -X POST https://5965-38-25-25-217.ngrok-free.app/api/v1/users/register \
            -H "Content-Type: application/json" \
            -d '{
              "username": "${{ github.event.inputs.username }}",
              "email": "${{ github.event.inputs.email }}",
              "password": "${{ github.event.inputs.password }}"
            }')
          echo "HTTP_CODE=$response" >> $GITHUB_ENV
          echo "RESPONSE_BODY=$(cat response_body.txt)" >> $GITHUB_ENV

      - name: Verificar registro
        run: |
          if [ "${{ env.HTTP_CODE }}" -ne 201 ]; then
            echo "Error en el registro de usuario"
            echo "${{ env.RESPONSE_BODY }}"
            exit 1
          fi
          echo "Usuario registrado exitosamente"
          echo "${{ env.RESPONSE_BODY }}"
        