name: User Registration Workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username del usuario'
        required: true
        type: string
      email:
        description: 'Email del usuario'
        required: true
        type: string
      password:
        description: 'Contraseña del usuario'
        required: true
        type: string

jobs:
    register-user:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Register User
            id: register
            run: |
                response=$(curl -s -w "%{http_code}" -o response.txt -X POST http://localhost:3000/api/v1/register \
                    -H "Content-Type: application/json" \
                    -d '{
                    "username": "${{ github.event.inputs.username }}",
                    "email": "${{ github.event.inputs.email }}",
                    "password": "${{ github.event.inputs.password }}"
                    }')
                http_code=$(tail -n1 <<< "$response")
                if [ "$http_code" -ne 200 ]; then
                    echo "Error en el registro de usuario"
                    cat response.txt
                    exit 1
                fi
                echo "Usuario registrado exitosamente"
                cat response.txt
          
          - name: Verificar registro
            if: steps.register.outcome != 'success'
            run: |
              echo "Error en el registro de usuario"
              echo "response: ${{ steps.register.outputs.response }}"
              exit 1
          
          - name: Registro exitoso
            if: steps.register.outcome == 'success'
            run: |
              echo "Usuario registrado exitosamente"
              echo "response: ${{ steps.register.outputs.response }}"
        

        
        